### ISSUE TITLE
Content-Type header issue

### ISSUE THREAD

**Issue by geoffwc** [kkazuo/dart-azblob#13]
This library has been really helpful so thanks for all the hard work on it!

I found an issue yesterday, which took a while to figure out what was going on.

I'm setting content type for an image upload, but when the signature is created it is adding an array object instead of the single content type. The server must strip the single content-type from the array before it computes the hash so it doesn't match.

`final mimeType = lookupMimeType(fileName);

      final azureStorage = AzureStorage.parse(cloudStorageAccount);
      await azureStorage.putBlob(blobUrl,
          bodyBytes: bodyBytes, contentType: mimeType);`

It's a simple fix to get firstOrNull to get the first content type (I can't see there being mixed types for this use case):

`final ct = request.headers['Content-Type']?.firstOrNull ?? '';`

Happy to raise a PR, I tried to create a fork but couldn't push to it. Do I need to be a contributer?

**Comment by kkazuo** [comment]
@geoffwc Thank you for digging the problem of this library.
I’m sorry for your inconviniences.
I apreciate the PR.
I’m not a GitHub guru, so I may be misconfigured something on GH.
Please retry push PR, or show me the patch diff I can merge.

**Comment by geoffwc** [comment]
Hey @kkazuo not an inconvenience hope I can help
I think you might add me as a contributor. I can't even push to my fork.
Thanks

**Comment by geoffwc** [comment]
Thanks @kkazuo works nicely. I can delete my hacked version now

**Comment by kkazuo** [comment]
Thanks @geoffwc confirming the fix.
I close the issue now.
Thank you
