### ISSUE TITLE
Delete 

### ISSUE THREAD

**Issue by GabeDiamond** [kkazuo/dart-azblob#4]
Thank you very much for creating this package! It's been very helpful to me. I recently found myself needing functionality to delete a file within azure blob storage. I implemented this with the following:

```
Future<http.StreamedResponse> deleteBlob(String path) async {
    var request = http.Request('DELETE', uri(path: path));
    sign(request);
    return request.send();
  }
```

Please let me know if you find this helpful and would like to add this, or would like a pull request for it.

**Comment by kkazuo** [comment]
hi @GabeDiamond , it looks good to me. and pull requests are welcome!
thank you

**Comment by GabeDiamond** [comment]
Great! I put in a pull request. This is actually my first open source pull request, so please let me know if I didn't do it correctly.

**Comment by kkazuo** [comment]
It looks good.
I'll upload a new version to pub.dev.
Thank you.
