### ISSUE TITLE
Add Listing support for a Container

### ISSUE THREAD

**Issue by rkhetan** [kkazuo/dart-azblob#9]
Adding support for following Azure Blob REST API: https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=azure-ad

**Comment by kkazuo** [comment]
Yeah, that's interesting.

**Comment by kkazuo** [comment]
@rkhetan I have add `listBlobsRaw` new API as version 2.6.0.

```dart
var res = await storage.listBlobsRaw('your_container/your_prefix');
var xml = await res.stream.bytesToString();
```

This is raw API and it does not parse XML.

Thanks,

**Comment by kkazuo** [comment]
Cloud you try listBlobsRaw API?
Yes, It’s too low level interfcace, just returns XML data as-is.
But I don’t want to include some XML parser in this library.
I think Azure Blob Listing XML parser would be an another library if there are.
So I close the issue for now.

Thank you,
